name: dart_vscode
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  js: ^0.6.7
  node_preamble: ^2.0.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^2.0.0
  typings:
    path: ../typings/typings
